### ISSUE TITLE
Dioxus web Hot Reload issue

### ISSUE THREAD

**Issue by serzhiio** [DioxusLabs/cli#103]
It seems something going wrong.
If i run `dioxus server` i see `(index):32 WebSocket connection to 'ws://localhost:8080/_dioxus/ws' failed: ...`
If i run `dioxus serve --hot-reload` i see no errors, but no changes are visible after i update source code.
And why are there two WS connections when using `--hot-reload`: `/_dioxus/ws` and `/_dioxus/hot_reload`?

**Comment by serzhiio** [comment]
```
thread 'notify-rs inotify loop' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/serzh-dev/dev/dioxus/packages/rsx/src/hot_reload/hot_reloading_file_map.rs:64:46
stack backtrace:
   0: rust_begin_unwind
             at /rustc/5243ea5c29b136137c36bd773e5baa663790e097/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/5243ea5c29b136137c36bd773e5baa663790e097/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/5243ea5c29b136137c36bd773e5baa663790e097/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/5243ea5c29b136137c36bd773e5baa663790e097/library/core/src/result.rs:1090:23
   4: dioxus_rsx::hot_reload::hot_reloading_file_map::FileMap<Ctx>::update_rsx
             at /home/serzh-dev/dev/dioxus/packages/rsx/src/hot_reload/hot_reloading_file_map.rs:64:24
   5: dioxus_cli::server::startup_hot_reload::{{closure}}::{{closure}}
             at /home/serzh-dev/dev/cli/src/server/mod.rs:187:31
   6: <F as notify::EventHandler>::handle_event
             at /home/serzh-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.1.0/src/lib.rs:252:9
   7: notify::inotify::EventLoop::handle_inotify
             at /home/serzh-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.1.0/src/inotify.rs:401:37
   8: notify::inotify::EventLoop::handle_event
             at /home/serzh-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.1.0/src/inotify.rs:170:17
   9: notify::inotify::EventLoop::event_loop_thread
             at /home/serzh-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.1.0/src/inotify.rs:151:17
  10: notify::inotify::EventLoop::run::{{closure}}
             at /home/serzh-dev/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-5.1.0/src/inotify.rs:133:23

```

**Comment by Demonthos** [comment]
> It seems something going wrong.
> If i run `dioxus server` i see `(index):32 WebSocket connection to 'ws://localhost:8080/_dioxus/ws' failed: ...`

The dioxus-web crate will always try to connect to hot reloading even if the server does not have it enabled in debug mode

> If i run `dioxus serve --hot-reload` i see no errors, but no changes are visible after i update source code. 

I tried to reproduce this by installing the cli from this branch https://github.com/DioxusLabs/cli/pull/104 and hot reloading with a hello world example, and it worked. This error is probably something specific to either the code that you are hot reloading or something about your system that is broken with the CLI.
Can you provide more information about what code you are trying to hot reload (especially the directory structure of your code), your device info (OS, etc.)?, and the CLI version you are using

#105 changes IO errors to be logged instead of panicking which should fix the `"No such file or directory"` error panicking

> Why are there two WS connections when using `--hot-reload`: `/_dioxus/ws` and `/_dioxus/hot_reload`?

The `/_dioxus/hot_reload` connection is initiated by rust in the `dioxus-web` crate. The `/_dioxus/ws` is initiated by javascript with some code injected by the CLI. The `/_dioxus/hot_reload` could potentially be used with any CLI-like program or even a drag and drop interface, not just the CLI.

**Comment by serzhiio** [comment]
I was finally able to install latest git CLI version and it is working just fine.
Thx for explnations.
