### ISSUE TITLE
question(bundler): how does dioxus-cli improve upon tauri bundler?

### ISSUE THREAD

**Issue by sdwoodbury** [DioxusLabs/cli#125]
Hello,

I'm working on making windows/mac/linux installers for a Dioxus desktop app. I'm looking for the quickest easiest way to get up and running without reinventing the wheel. I appreciate how much work it is to automate the process of creating installers, and sought to understand how the provided tools work before deciding which one to use. I see that the Dioxus CLI uses tauri bundler, which uses cargo-bundle. My question is this:

Specifically in the context of creating installers for desktop applications, does the Dioxus CLI do anything which the tauri bundler doesn't do?

**Comment by Demonthos** [comment]
The Dioxus CLI bundler introduced in #118 uses the Tauri bundler library under the hood but works with the existing Dioxus.toml file. Both bundlers should function the same, the Dioxus bundler just integrates with the existing CLI and configuration better. However, the Dioxus CLI bundler is much more early in development and has less documentation. We have had reports of some platforms being broken. Currently the Tauri bundler is a more mature option. I would recommend avoiding the cargo-bundle command currently because support for windows in lacking compared to the Tauri bundler.
